# Generated by Django 3.2.21 on 2023-10-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dko5fxoa0/image/upload/v1/media/images/default_profile_p6k88b', upload_to='images/'),
        ),
    ]
